---
- name: Add user
  hosts: futurama
  gather_facts: no
  become: no

  tasks:
          - name: Add user
            user:
                    name: secureuser
                    password: password123
                    state: absent
            become: yes

