---
- name: Push a script to our host and run it
  hosts: futurama
  gather_facts: yes

  tasks:
          - name: run our python script
            script: ~/ans/py/holamundo.py
            args:
                    executable: python3
            register: results

          - name: What did holamundo produce
            debug:
                    var: results
